- name: Grafana - Create Prometheus Datasource
  community.grafana.grafana_datasource:
    name: "PrometheusDataSource"
    uid: "{{ GRAFANA_PROMETHEUS_DATASOURCE_UID }}" # Hardcode uid to make importing dashboards work properly
    grafana_url: "{{ GRAFANA_URL }}"
    grafana_api_key: "{{ grafana_api_key }}" # Inherited from parent playbook/tasks
    ds_type: "prometheus"
    ds_url: "{{ PROMETHEUS_URL }}"
    database: "{{ PROMETHEUS_DB }}"
    #user: "{{ INFLUXDB_USER }}"
    is_default: false
    sslmode: disable
    tls_skip_verify: true
  tags:
  - grafana-setup

- name: Grafana - Import Default Dashboards
  community.grafana.grafana_dashboard:
    grafana_url: "{{ GRAFANA_URL }}"
    grafana_api_key: "{{ grafana_api_key }}"
    validate_certs : false
    commit_message: Updated by ansible
    overwrite: false
    path: "{{ role_path }}/files/{{ item }}"
  loop:
  - SystemMonitorAllPrometheus.json
  - MetricInfoPrometheus.json
  ignore_errors: true
  tags:
  - grafana-setup