{{- define "shared-lib.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data: 
{{- range $key, $val := .Values.env }}
  - name: {{ lower $key }}
    value: {{ $val | quote }}
{{- end }}
{{- end }}