{{- define "shared-lib.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shared-lib.fullname" . }}
  labels:
    {{- include "shared-lib.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
    {{- end }}
  selector:
    {{- include "shared-lib.selectorLabels" . | nindent 4 }}
{{- end -}}