{{- define "shared-lib.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData: 
{{- range $key, $val := .Values.envSecrets }}
  "{{ $.Release.Name }}-{{ lower $key }}": {{ $val | quote }}
{{- end }}
{{- end }}