{{- define "shared-lib.secret" -}}
{{ $name := print .Release.Name "-" .Chart.Name "-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
stringData: 
{{- range $key, $val := .Values.envSecrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}