apiVersion: v2
name: app
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: activemq
    version: 0.1.0
    condition: activemq.enabled
    tags:
      - activemq
  - name: grafana
    version: ~8.1.1 # Version of the helm chart not the application
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    tags:
      - grafana
  - name: influxpump
    version: 0.1.0
    condition: influxpump.enabled
    tags:
      - influxpump
  - name: mlpump
    version: 0.1.0
    condition: mlpump.enabled
    tags:
      - mlpump
  - name: prometheus
    version: ~25.22.0 # Version of the helm chart not the application
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    tags:
      - prometheus
  - name: prometheuspump
    version: 0.1.0
    condition: prometheuspump.enabled
    tags:
      - prometheuspump
  - name: redfishread
    version: 0.1.0
    condition: redfishread.enabled
    tags:
      - redfishread
  - name: simpleauth
    version: 0.1.0
    condition: simpleauth.enabled
    tags:
      - simpleauth
  - name: simpledisc
    version: 0.1.0
    condition: simpledisc.enabled
    tags:
      - simpledisc