---
# tasks file for k8s-metallb
- name: Preparation
  ansible.builtin.shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e 's/strictARP: false/strictARP: true/' | kubectl apply -f - -n kube-system"
  register: res
  changed_when: res.rc != 0

#- name: Install
#  ansible.builtin.shell: |
#    kubectl create namespace metallb-system
#    helm install metallb metallb/metallb --namespace metallb-system
#    kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
#  register: res
#  changed_when: res.rc != 0

- name: Generate IPAddressPool config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /tmp/config.yml
    mode: "0755"

- name: Apply IPAddressPool
  ansible.builtin.shell: kubectl apply -f /tmp/config.yml
  register: res
  changed_when: res.rc != 0

- name: Generate L2Advertisement config
  ansible.builtin.template:
    src: l2advertisement.yml.j2
    dest: /tmp/l2advertisement.yml
    mode: "0755"

- name: Apply L2Advertisement
  ansible.builtin.shell: kubectl apply -f /tmp/l2advertisement.yml
  register: res
  changed_when: res.rc != 0