---
# defaults file for idrac-setup
stomphost: activemq
stompport: 61613

idrac_attributes: 
  # Enable Telemetry Globally
  Telemetry.1.EnableTelemetry: "Enabled"
  # Enable individual Metric Reports
  TelemetryCPUSensor.1.EnableTelemetry: "Enabled"
  TelemetryFanSensor.1.EnableTelemetry: "Enabled"
  TelemetryMemoryMetrics.1.EnableTelemetry: "Enabled"
  TelemetryMemorySensor.1.EnableTelemetry: "Enabled"
  TelemetryNICSensor.1.EnableTelemetry: "Enabled"
  TelemetryNICStatistics.1.EnableTelemetry: "Enabled"
  TelemetryPowerMetrics.1.EnableTelemetry: "Enabled"
  TelemetryPSUMetrics.1.EnableTelemetry: "Enabled"
  TelemetrySensor.1.EnableTelemetry: "Enabled"
  TelemetrySFPTransceiver.1.EnableTelemetry: "Enabled"
  TelemetryStorageDiskSMARTData.1.EnableTelemetry: "Enabled"
  TelemetryStorageSensor.1.EnableTelemetry: "Enabled"
  TelemetrySystemUsage.1.EnableTelemetry: "Enabled"
  TelemetryThermalMetrics.1.EnableTelemetry: "Enabled"
  TelemetryThermalSensor.1.EnableTelemetry: "Enabled"
  #TelemetryGPUMetrics.1.EnableTelemetry: "Enabled"
  #TelemetryGPUStatistics.1.EnableTelemetry: "Enabled"
  # Enable Redfish Alerts (Events)
  RedfishEventing.1.EventEnable: "Enabled"
  # Setup NTP and Timezone so the time will be set properly, otherwise data might appear "missing" when really it's just time shifted
  NTPConfigGroup.1.NTPEnable: "Enabled"
  NTPConfigGroup.1.NTP1: "time-a-g.nist.gov"
  Time.1.Timezone: "US/Central"
