- op: add
  path: /machine/sysctls
  value:
    vm.nr_hugepages: "1024"

- op: add
  path: /machine/nodeLabels
  value:
    openebs.io/engine: "mayastor"

- op: add
  path: /machine/disks
  value:
    - device: /dev/sdb
      partitions:
        - mountpoint: /var/mnt/storage

- op: add
  path: /machine/kubelet/extraMounts
  value:
    - destination: /var/openebs/local
      type: bind
      source: /var/mnt/storage
      options:
        - bind
        - rshared
        - rw