---
# tasks file for telemetry-demo

- name: Generate docker-compose.yaml file
  template: 
    dest: "{{ docker_compose_file }}"
    src: docker-compose.yaml.j2
  tags:
    - generate-docker-compose

- name: Create empty .env file if it doesn't exist already
  copy:
    content: ""
    dest: "{{ docker_env_file }}"
    force: false