name: Docker Image Publish

on:
  push:
    branches: [ "test" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image: ghcr.io/TrevorSquillario/influxpump
            cmd: influxpump
          - dockerfile: Dockerfile.ml
            image: ghcr.io/TrevorSquillario/mlpump
            cmd: mlpump
          - dockerfile: Dockerfile
            image: ghcr.io/TrevorSquillario/prometheuspump
            cmd: prometheuspump
          - dockerfile: Dockerfile
            image: ghcr.io/TrevorSquillario/redfishread
            cmd: redfishread
          - dockerfile: Dockerfile
            image: ghcr.io/TrevorSquillario/simpleauth
            cmd: simpleauth
          - dockerfile: Dockerfile
            image: ghcr.io/TrevorSquillario/simpledisc
            cmd: simpledisc
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image 
        uses: docker/build-push-action@v6
        with:
          context: ./docker-compose
          file: ./docker-compose/${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CMD=${{ matrix.cmd }}